### ISSUE TITLE
OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by certik** [hashdist/hashdist#113]
```
[ERROR] Uncaught exception:
Traceback (most recent call last):
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/_hashdist/hashdist/cli/main.py", line 136, in help_on_exceptions
    return func(*args, **kw)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/builder/builder.py", line 311, in main
    profile_aid, imports = ctx.build_all(packages, 'profile')
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/builder/builder.py", line 64, in build_all
    dep_spec, imports = visit(root_name)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/builder/builder.py", line 56, in visit
    spec, _ = visit(dep)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/builder/builder.py", line 58, in visit
    artifact_id = build_package(self, pkg, imports)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/builder/builder.py", line 121, in build_package
    artifact_id, dir = ctx.build_store.ensure_present(buildspec, ctx.config, keep_build='error')
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/_hashdist/hashdist/core/build_store.py", line 413, in ensure_present
    artifact_dir = builder.build(config, keep_build)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/_hashdist/hashdist/core/build_store.py", line 510, in build
    self.build_to(artifact_dir, config, keep_build)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/_hashdist/hashdist/core/build_store.py", line 542, in build_to
    self.build_store.remove_build_dir(build_dir)
  File "/auto/nest/nest/u/ondrej/repos/python-hpcmp2/_hashdist/hashdist/core/build_store.py", line 495, in remove_build_dir
    shutil.rmtree(build_dir)
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/auto/netscratch/ondrej/bld/libtool-n-6thc'

This exception has not been translated to a human-friendly error message,
please file an issue at https://github.com/hashdist/hashdist/issues pasting
this stack trace.
```

**Comment by certik** [comment]
So I got hit by this again:
```certik@ml-fey2:~/repos/hashstack(moonlight)$ hit build -j8  
/yellow/users/certik/repos/hashdist/hashdist/formats/marked_yaml.py:72: DeprecationWarning: object.__init__() takes no parameters
  cls.__init__(self, x)
[cmake] Building cmake/7j6vg4fc4ohx, follow log with:
[cmake]   tail -f /panfs/scratch/avol8/certik/h/tmp/cmake-7j6vg4fc4ohx-1/build.log
[CRITICAL] Uncaught exception:
[CRITICAL] Traceback (most recent call last):
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
[CRITICAL]     return func(*args, **kw)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
[CRITICAL]     retcode = args.subcommand_handler(ctx, args)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/cli/frontend_cli.py", line 51, in run
[CRITICAL]     self.profile_builder_action()
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/cli/frontend_cli.py", line 108, in profile_builder_action
[CRITICAL]     self.args.k, self.args.debug)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/spec/builder.py", line 150, in build
[CRITICAL]     keep_build=keep_build, debug=debug)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/core/build_store.py", line 379, in ensure_present
[CRITICAL]     artifact_dir = builder.build(config, keep_build)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/core/build_store.py", line 554, in build
[CRITICAL]     self.build_to(artifact_dir, config, keep_build)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/core/build_store.py", line 586, in build_to
[CRITICAL]     self.build_store.remove_build_dir(build_dir)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/core/build_store.py", line 427, in remove_build_dir
[CRITICAL]     robust_rmtree(build_dir, self.logger)
[CRITICAL]   File "/yellow/users/certik/repos/hashdist/hashdist/core/fileutils.py", line 89, in robust_rmtree
[CRITICAL]     shutil.rmtree(path)
[CRITICAL]   File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python2.6/shutil.py", line 221, in rmtree
[CRITICAL]     onerror(os.rmdir, path, sys.exc_info())
[CRITICAL]   File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python2.6/shutil.py", line 219, in rmtree
[CRITICAL]     os.rmdir(path)
[CRITICAL] OSError: [Errno 39] Directory not empty: '/panfs/scratch/avol8/certik/h/tmp/cmake-7j6vg4fc4ohx-1'
[CRITICAL] This exception has not been translated to a human-friendly error message,
[CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
[CRITICAL] this stack trace.
```

**Comment by certik** [comment]
I bet it has something to do with the `logger`: https://github.com/hashdist/hashdist/blob/a1ee86476a7c3c533e47f40cf0a39e516cd9ed6c/hashdist/core/fileutils.py#L82, as I didn't see any message warning me I need to turn of `tail -f` in the separate terminal, otherwise it will fail to install perfectly fine package (that BTW took **forever** to install, thanks to slow NFS), thanks Hashdist.
