### ISSUE TITLE
Tarball can't be unpacked

### ISSUE THREAD

**Issue by certik** [hashdist/hashdist#234]
Create `pkgs/fflas_ffpack.yaml` with this contents:

```
extends: [autotools_package]

dependencies:
  build: [gmp]

sources:
- url: http://linalg.org/fflas-ffpack-1.6.0.tar.gz
  key: tar.gz:jhsz3hdckjlvxhtahvcowukmhujdsqc2

build_stages:
- name: configure
  extra: ['--with-gmp=$GMP_DIR']
```

and try to build it. You get:

```
ondrej@eagle:~/repos/hashstack(linbox)$ hit build -v
Created build dir: /home/ondrej/.hashdist/tmp/fflas_ffpack-3hhj4gufzant-5
[fflas_ffpack] Building fflas_ffpack/3hhj4gufzant
Unpacking sources files:wih3sztwvczzg2v6edbaeb2etzbnujnb
Unpacking sources tar.gz:jhsz3hdckjlvxhtahvcowukmhujdsqc2
[ERROR] Uncaught exception:
Traceback (most recent call last):
  File "/home/ondrej/usr/bin/hit", line 13, in <module>
    sys.exit(help_on_exceptions(logger, main, sys.argv, os.environ, logger))
  File "/home/ondrej/repos/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
    logger.error("Uncaught exception:")
  File "/home/ondrej/repos/hashdist/hashdist/hdist_logging.py", line 167, in error
    self.log(ERROR, msg, *args)
  File "/home/ondrej/repos/hashdist/hashdist/hdist_logging.py", line 146, in log
    stream.write(msg + "\n")
ValueError: I/O operation on closed file
ondrej@eagle:~/repos/hashstack(linbox)$ DEBUG=1 hit build -v
Created build dir: /home/ondrej/.hashdist/tmp/fflas_ffpack-3hhj4gufzant-6
[fflas_ffpack] Building fflas_ffpack/3hhj4gufzant
Unpacking sources files:wih3sztwvczzg2v6edbaeb2etzbnujnb
Unpacking sources tar.gz:jhsz3hdckjlvxhtahvcowukmhujdsqc2
Traceback (most recent call last):
  File "/home/ondrej/usr/bin/hit", line 13, in <module>
    sys.exit(help_on_exceptions(logger, main, sys.argv, os.environ, logger))
  File "/home/ondrej/repos/hashdist/hashdist/cli/main.py", line 169, in help_on_exceptions
    return func(*args, **kw)
  File "/home/ondrej/repos/hashdist/hashdist/cli/main.py", line 143, in main
    retcode = args.subcommand_handler(ctx, args)
  File "/home/ondrej/repos/hashdist/hashdist/cli/frontend_cli.py", line 42, in run
    self.profile_builder_action()
  File "/home/ondrej/repos/hashdist/hashdist/cli/frontend_cli.py", line 98, in profile_builder_action
    self.args.k, self.args.debug)
  File "/home/ondrej/repos/hashdist/hashdist/spec/builder.py", line 151, in build
    keep_build=keep_build, debug=debug)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 377, in ensure_present
    artifact_dir = builder.build(config, keep_build)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 551, in build
    self.build_to(artifact_dir, config, keep_build)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 570, in build_to
    self.run_build_commands(build_dir, artifact_dir, env, config)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 627, in run_build_commands
    self.build_store.prepare_build_dir(config, logger, self.build_spec, build_dir)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 430, in prepare_build_dir
    unpack_sources(self.logger, source_cache, build_spec.doc.get('sources', []), target_dir)
  File "/home/ondrej/repos/hashdist/hashdist/core/build_store.py", line 656, in unpack_sources
    source_cache.unpack(key, target)
  File "/home/ondrej/repos/hashdist/hashdist/core/source_cache.py", line 376, in unpack
    handler.unpack(type, hash, target_path)
  File "/home/ondrej/repos/hashdist/hashdist/core/source_cache.py", line 801, in unpack
    create_archive_handler(type).unpack(infile, target_dir, hash)
  File "/home/ondrej/repos/hashdist/hashdist/core/source_cache.py", line 882, in unpack
    archive.extractall(target_dir, members)
  File "/usr/lib/python2.7/tarfile.py", line 2048, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2085, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2169, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2254, in makelink
    self._extract_member(self._find_link_target(tarinfo), targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2410, in _find_link_target
    raise KeyError("linkname %r not found" % linkname)
KeyError: "linkname 'fflas-ffpack-1.6.0/fflas-ffpack/utils/args-parser.h' not found"
```

The first error is useless, due to #233, but you can enable the true error with `DEBUG=1`. The error seems either in `tarfile.py`, or in the way we use it. Raising to high priority, as this prevents me to create the package.

**Comment by jcftang** [comment]
I've made an initial attempt to flatten out symlinks in #304
