### ISSUE TITLE
LZMA on OSX mavericks -- better error messages needed

### ISSUE THREAD

**Issue by jcftang** [hashdist/hashdist#258]
Error reporting on missing lzma isn't great

<pre>
[jtang@laplace hashstack2 (wip-coreutils)]$ hit fetch http://ftp.gnu.org/gnu/coreutils/coreutils-8.22.tar.xz
Downloading http://ftp.gnu.org/gnu/coreutils/coreutils-8.22.tar.xz...
Downloading 'http://ftp.gnu.org/gnu/coreutils/coreutils-8.22.tar.xz'
[=========================] 100.0% (5.1MB of 5.1MB) 0.775MB/s ETA 0s
[ERROR] Uncaught exception:
Traceback (most recent call last):
  File "/Users/jtang/develop/hashdist/hashdist/cli/main.py", line 173, in help_on_exceptions
    return func(*args, **kw)
  File "/Users/jtang/develop/hashdist/hashdist/cli/main.py", line 147, in command_line_entry_point
    retcode = args.subcommand_handler(ctx, args)
  File "/Users/jtang/develop/hashdist/hashdist/cli/source_cache_cli.py", line 80, in run
    key = store.fetch_archive(args.url, args.type)
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 285, in fetch_archive
    return ArchiveSourceCache(self).fetch_archive(url, type, None)
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 764, in fetch_archive
    return self._download_archive(url, type, expected_hash)
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 768, in _download_archive
    temp_file, hash = self._download_and_hash(url, type)
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 720, in _download_and_hash
    if not create_archive_handler(type).verify(temp_path):
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 851, in verify
    with closing(self.tarfileobj_from_name(filename)) as tarfileobj:
  File "/Users/jtang/develop/hashdist/hashdist/core/source_cache.py", line 912, in tarfileobj_from_name
    import lzma
ImportError: No module named lzma

This exception has not been translated to a human-friendly error message,
please file an issue at https://github.com/hashdist/hashdist/issues pasting
this stack trace.
</pre>

**Comment by vbraun** [comment]
Just realized that OSX doesn't ship with lzma, thanks a bunch Apple.

IMHO this means we are broken; Solutions are 
* either build & use our own lzma + python (somewhat tricky bootstrapping), or
* disallow .xz tarballs in hashstack

**Comment by jcftang** [comment]
In https://github.com/hashdist/hashdist/pull/333 there is at least a warning, it's just waiting to be merged

**Comment by certik** [comment]
I bootstrap using https://github.com/hashdist/hashstack/blob/d978b36df6dcdaab43c18996e9986cbdce26c618/examples/hd_base.Darwin.yaml, as you can see, I build gcc (gfortran is needed) and lzma. Then I use this profile to build everything else, see https://github.com/hashdist/hashstack/pull/779. I can either add the `hd_base` profile into `PATH`, so that `hit` finds lzma, or perhaps I can just install `hashdist` into this profile directly (I currently do not do this).

**Comment by certik** [comment]
I can't remember if I tested lzma on Mac yet or not, I know I tested it on linux and it works (my RHEL6 doesn't have lzma either) by putting the `hd_base` profile into `PATH`.
