### ISSUE TITLE
test failures when tests are run via tox

### ISSUE THREAD

**Issue by jcftang** [hashdist/hashdist#311]
I've been poking at the tests a bit and noticed this...

```
$ tox
GLOB sdist-make: /Users/jtang/develop/hashdist/setup.py
py26 inst-nodeps: /Users/jtang/develop/hashdist/.tox/dist/hashdist-0.3.zip
py26 runtests: PYTHONHASHSEED='1972318162'
py26 runtests: commands[0] | nosetests --with-doctest
..........S...../Users/jtang/develop/hashdist/hashdist/core/test/test_build_store.py:208: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  assert "collide in first 12 chars" in e.exc_val.message
....S...........................S.....S.................Downloading /tmp/foo/garbage.tar.gz...
Downloading http://localhost:999/foo.tar.gz...
..................../Users/jtang/develop/hashdist/hashdist/formats/marked_yaml.py:72: DeprecationWarning: object.__init__() takes no parameters
  cls.__init__(self, x)
...S.........F......................................
======================================================================
FAIL: hashdist.spec.tests.test_package.test_load_and_inherit_package
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jtang/develop/hashdist/.tox/py26/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jtang/develop/hashdist/hashdist/spec/tests/test_package.py", line 247, in test_load_and_inherit_package
    eq_(expected, loader.doc)
AssertionError: {'dependencies': {'build': ['dep1', 'dep_gp_1'], 'run': ['dep1', 'dep_base2_1']}, 'profile_links': [{'link': '*/**/*', 'name': 'start'}, {'link': 'foo', 'name': '__ypp7s5jlosieet6v4iyhvbg52ymlcwgk'}, {'link': '*/**/*', 'after': 'start', 'name': 'end'}], 'when_build_dependency': [{'set': 'FOO', 'value': 'foovalue', 'name': 'start'}], 'build_stages': [{'handler': 'foo', 'random': 'anonymous', 'name': '__3gcv3kvebeam4h3qzok75lxxt5n3rzr7'}, {'b': 3, 'a': 1, 'name': 'stage1_override'}, {'a': 1, 'name': 'stage4_replace'}, {'b': 3, 'a': 1, 'after': 'stage1_override', 'name': 'stage3_override'}, {'before': 'stage3_override', 'a': 1, 'after': 'stage1_override', 'name': 'stage_2_inserted'}], 'post_process': [{'hit': 'relative-rpath', 'name': 'post1'}]} != {'dependencies': {'build': ['dep1', 'dep_gp_1'], 'run': ['dep1', 'dep_base2_1']}, 'post_process': [{'hit': 'relative-rpath', 'name': 'post1'}], 'when_build_dependency': [{'set': 'FOO', 'value': 'foovalue', 'name': 'start'}], 'build_stages': [{'a': 1, 'name': 'stage4_replace'}, {'b': 3, 'a': 1, 'name': 'stage1_override'}, {'random': 'anonymous', 'handler': 'foo', 'name': '__3gcv3kvebeam4h3qzok75lxxt5n3rzr7'}, {'b': 3, 'a': 1, 'after': 'stage1_override', 'name': 'stage3_override'}, {'before': 'stage3_override', 'a': 1, 'after': 'stage1_override', 'name': 'stage_2_inserted'}], 'profile_links': [{'link': 'foo', 'name': '__ypp7s5jlosieet6v4iyhvbg52ymlcwgk'}, {'link': '*/**/*', 'name': 'start'}, {'link': '*/**/*', 'after': 'start', 'name': 'end'}]}

----------------------------------------------------------------------
Ran 143 tests in 4.453s

FAILED (SKIP=5, failures=1)
ERROR: InvocationError: '/Users/jtang/develop/hashdist/.tox/py26/bin/nosetests --with-doctest'
py27 inst-nodeps: /Users/jtang/develop/hashdist/.tox/dist/hashdist-0.3.zip
py27 runtests: PYTHONHASHSEED='1972318162'
py27 runtests: commands[0] | nosetests --with-doctest
..........S.........S...........................S.....S.................Downloading /tmp/foo/garbage.tar.gz...
Downloading http://localhost:999/foo.tar.gz...
.......................S.........F......................................
======================================================================
FAIL: hashdist.spec.tests.test_package.test_load_and_inherit_package
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jtang/develop/hashdist/.tox/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jtang/develop/hashdist/hashdist/spec/tests/test_package.py", line 247, in test_load_and_inherit_package
    eq_(expected, loader.doc)
AssertionError: {'dependencies': {'build': ['dep1', 'dep_gp_1'], 'run': ['dep1', 'dep_base2_1']}, 'profile_links': [{'link': '*/**/*', 'name': 'start'}, {'link': 'foo', 'name': '__ypp7s5jlosieet6v4iyhvbg52ymlcwgk'}, {'link': '*/**/*', 'after': 'start', 'name': 'end'}], 'when_build_dependency': [{'set': 'FOO', 'value': 'foovalue', 'name': 'start'}], 'build_stages': [{'handler': 'foo', 'random': 'anonymous', 'name': '__3gcv3kvebeam4h3qzok75lxxt5n3rzr7'}, {'b': 3, 'a': 1, 'name': 'stage1_override'}, {'a': 1, 'name': 'stage4_replace'}, {'b': 3, 'a': 1, 'after': 'stage1_override', 'name': 'stage3_override'}, {'before': 'stage3_override', 'a': 1, 'after': 'stage1_override', 'name': 'stage_2_inserted'}], 'post_process': [{'hit': 'relative-rpath', 'name': 'post1'}]} != {'dependencies': {'build': ['dep1', 'dep_gp_1'], 'run': ['dep1', 'dep_base2_1']}, 'post_process': [{'hit': 'relative-rpath', 'name': 'post1'}], 'when_build_dependency': [{'set': 'FOO', 'value': 'foovalue', 'name': 'start'}], 'build_stages': [{'a': 1, 'name': 'stage4_replace'}, {'b': 3, 'a': 1, 'name': 'stage1_override'}, {'random': 'anonymous', 'handler': 'foo', 'name': '__3gcv3kvebeam4h3qzok75lxxt5n3rzr7'}, {'b': 3, 'a': 1, 'after': 'stage1_override', 'name': 'stage3_override'}, {'before': 'stage3_override', 'a': 1, 'after': 'stage1_override', 'name': 'stage_2_inserted'}], 'profile_links': [{'link': 'foo', 'name': '__ypp7s5jlosieet6v4iyhvbg52ymlcwgk'}, {'link': '*/**/*', 'name': 'start'}, {'link': '*/**/*', 'after': 'start', 'name': 'end'}]}

----------------------------------------------------------------------
Ran 143 tests in 4.512s

FAILED (SKIP=5, failures=1)
ERROR: InvocationError: '/Users/jtang/develop/hashdist/.tox/py27/bin/nosetests --with-doctest'
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
ERROR:   py26: commands failed
ERROR:   py27: commands failed
```

**Comment by vbraun** [comment]
I just noticed this as well; it is because the order in profile_links and build_stages is different
