### ISSUE TITLE
OSX cannot download openssl

### ISSUE THREAD

**Issue by vbraun** [hashdist/hashdist#352]
Presumably thats because openssl.org stopped accepting SSLv3; Need TLSv1.1+ to connect now:
~~~
[...]
[pkg-config] Building pkg-config/7jewco2e427y, follow log with:
[pkg-config]   tail -f /Users/vbraun/.hashdist/tmp/pkg-config-7jewco2e427y/_hashdist/build.log
Downloading https://www.openssl.org/source/openssl-1.0.1g.tar.gz...
[ERROR] urllib failed to download (reason: EOF occurred in violation of protocol (_ssl.c:590)): https://www.openssl.org/source/openssl-1.0.1g.tar.gz
Downloading https://www.openssl.org/source/openssl-1.0.1g.tar.gz...
[ERROR] urllib failed to download (reason: EOF occurred in violation of protocol (_ssl.c:590)): https://www.openssl.org/source/openssl-1.0.1g.tar.gz
Downloading https://www.openssl.org/source/openssl-1.0.1g.tar.gz...
[ERROR] urllib failed to download (reason: EOF occurred in violation of protocol (_ssl.c:590)): https://www.openssl.org/source/openssl-1.0.1g.tar.gz
[CRITICAL] You may wish to check your Internet connection or the remote server
~~~
I do have a working internet connection and can download openssl by hand.

**Comment by vbraun** [comment]
PS: Vanilla Python on OSX 10.11:
~~~~
$ python
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> urllib2.urlopen('https://www.openssl.org/source/openssl-1.0.1g.tar.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
~~~~

**Comment by vbraun** [comment]
Looks like OSX openssl only supports TLSv1 but nothing later. But openssl.org requires TLSv1.1 or later.
~~~~
$ openssl s_client -tls1 -connect www.openssl.org:443  # OSX
CONNECTED(00000003)
57527:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/ssl/s3_pkt.c:566:
$ openssl s_client -tls1 -connect www.openssl.org:443    # Linux
CONNECTED(00000003)
140314624292728:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:617:
~~~
Linux supports `-tlsv1_1` and that works, but OSX doesn't know `-tlsv1_1`

**Comment by vbraun** [comment]
Renaming this since its generic to OSX: No TLSv1.1 support in urllib2.

**Comment by certik** [comment]
If we compile our own openssl, will this work?

So the only problem is how to bootstrap Hashdist the first time? Looks like we should provide a big tarball with all the sources, which you would do in Sage anyway.

**Comment by vbraun** [comment]
If we build our own openssl + Python and then run hashdist with the self-compiled python it would work. But thats annoying, to say the least.

**Comment by certik** [comment]
Yeah, it is. I do that on my RHEL6 system. I view the initial Hashstack installation is a base layer, essentially improving the old system utilities like gcc, openssl, Python, etc. I always load it in my `.bashrc`. Then I build the rest of Hashstack using it, and things work.

**Comment by dimpase** [comment]
For what's worth, Apple did fix its openssl (this is on OSX 10.12.6):
```
$ openssl s_client -tls1 -connect www.openssl.org:443
CONNECTED(00000005)
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/CN=www.openssl.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
...
```
I presume that it's still not 100% OK, as there are some `unable to get local issuer certificate` warnings/errors, but that's probably due to the machine missing some certs.
As well, the above `urllib2.urlopen('https://www.openssl.org/source/openssl-1.0.1g.tar.gz')`
test in Python2 returns an error indicating the certs problem---the protocol is supported though:
```
$ python
Python 2.7.13 (default, Mar 22 2017, 09:45:41) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> urllib2.urlopen('https://www.openssl.org/source/openssl-1.0.1g.tar.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
>>> 
```

**Comment by dimpase** [comment]
Scratch the python part of the previous comment - it was wrong python. With the right one, it just works:
```
$ python   
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> urllib2.urlopen('https://www.openssl.org/source/openssl-1.0.1g.tar.gz')
<addinfourl at 5672512 whose fp = <socket._fileobject object at 0x56d2f0>>
>>> 
```

**Comment by certik** [comment]
Cool, thanks!

**Comment by vbraun** [comment]
That doesn't look like Apple fixed its shit, its just openssl downgrading their security to allow the old TLSv1/SSLv3 again.
