### ISSUE TITLE
HashDist fenics instalation in a i7 6700 laptop falis due to lapack not finding my CPU architecture

### ISSUE THREAD

**Issue by lobandolerpi** [hashdist/hashdist#366]
Hello,

I am trying to install fenics foollowing this instructions that my supervisor gave me.    https://fenicsproject.org/download/installation_using_hashdist.html#installation-using-hashdist

I am not a linux expert, so if you have any answerr please try to be as low level as possible.

I succeded installing fenics in my PC however failed in my laptop. Both have ubuntu 16.04 OS. On the first run lapack package failed because it was not able to find a  my CPU architecture

log of the error:

2016/10/30 11:56:58 - INFO: [package:run_job] getarch_2nd.c:69:50: error: 'CGEMM_DEFAULT_Q' undeclared (first use in this function)
2016/10/30 11:56:58 - INFO: [package:run_job]      printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q \* CGEMM_DEFAULT_UNROLL_N \* 4 \* 2 \*  sizeof(float)));
2016/10/30 11:56:58 - INFO: [package:run_job]                                                   ^
2016/10/30 11:56:58 - INFO: [package:run_job] getarch_2nd.c:70:50: error: 'ZGEMM_DEFAULT_Q' undeclared (first use in this function)
2016/10/30 11:56:58 - INFO: [package:run_job]      printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q \* ZGEMM_DEFAULT_UNROLL_N \* 2 \* 2 \*  sizeof(double)));
2016/10/30 11:56:58 - INFO: [package:run_job]                                                   ^
2016/10/30 11:56:58 - INFO: [package:run_job] make: **\* [getarch_2nd] Error 1
2016/10/30 11:56:58 - INFO: [package:run_job] Makefile:131: **\* OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
2016/10/30 11:56:58 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
2016/10/30 11:56:58 - ERROR: [package:run_job] command failed (code=2); raising

After some browsing I  found this piece of advice and also that my processor i7 6700 is from the SKYLAKE line. Then I introduced the following to line into   fenics.yaml

blas:
  use: openblas
  extra_flags: TARGET=SKYLAKE

Now I am getting the following error in the terminal:

[CRITICAL] Uncaught exception:
[CRITICAL] Traceback (most recent call last):
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/cli/main.py", line 202, in help_on_exceptions
[CRITICAL]     return func(_args, *_kw)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/cli/main.py", line 174, in command_line_entry_point
[CRITICAL]     retcode = args.subcommand_handler(ctx, args)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/cli/frontend_cli.py", line 51, in run
[CRITICAL]     self = cls(ctx, args)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/cli/frontend_cli.py", line 46, in **init**
[CRITICAL]     self.profile = load_profile(self.ctx.logger, self.checkouts, args.profile, parameters)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/spec/profile.py", line 539, in load_profile
[CRITICAL]     doc = load_and_inherit_profile(checkout_manager, profile_file, None, override_parameters)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/spec/profile.py", line 484, in load_and_inherit_profile
[CRITICAL]     doc = load_yaml_from_file(checkouts.resolve(profile_file))
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/formats/marked_yaml.py", line 198, in load_yaml_from_file
[CRITICAL]     return marked_yaml_load(expanded_stream, filecaption)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/formats/marked_yaml.py", line 189, in marked_yaml_load
[CRITICAL]     return MarkedLoader(stream, filecaption).get_single_data()
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/constructor.py", line 37, in get_single_data
[CRITICAL]     node = self.get_single_node()
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 36, in get_single_node
[CRITICAL]     document = self.compose_document()
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 55, in compose_document
[CRITICAL]     node = self.compose_node(None, None)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 84, in compose_node
[CRITICAL]     node = self.compose_mapping_node(anchor)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 133, in compose_mapping_node
[CRITICAL]     item_value = self.compose_node(node, item_key)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 84, in compose_node
[CRITICAL]     node = self.compose_mapping_node(anchor)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 133, in compose_mapping_node
[CRITICAL]     item_value = self.compose_node(node, item_key)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 84, in compose_node
[CRITICAL]     node = self.compose_mapping_node(anchor)
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/composer.py", line 127, in compose_mapping_node
[CRITICAL]     while not self.check_event(MappingEndEvent):
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/parser.py", line 98, in check_event
[CRITICAL]     self.current_event = self.state()
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/parser.py", line 428, in parse_block_mapping_key
[CRITICAL]     if self.check_token(KeyToken):
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/scanner.py", line 115, in check_token
[CRITICAL]     while self.need_more_tokens():
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/scanner.py", line 149, in need_more_tokens
[CRITICAL]     self.stale_possible_simple_keys()
[CRITICAL]   File "/tmp/fenics-install.YEA8Fg/hashdist/hashdist/deps/yaml/scanner.py", line 289, in stale_possible_simple_keys
[CRITICAL]     "could not found expected ':'", self.get_mark())
[CRITICAL] ScannerError: while scanning a simple key
[CRITICAL]   in "/tmp/fenics-install.YEA8Fg/hashstack/default.yaml", line 30, column 5
[CRITICAL] could not found expected ':'
[CRITICAL]   in "/tmp/fenics-install.YEA8Fg/hashstack/default.yaml", line 31, column 3
[CRITICAL] This exception has not been translated to a human-friendly error message,
[CRITICAL] please file an issue at https://github.com/hashdist/hashdist/issues pasting
[CRITICAL] this stack trace.
Command exited with non-zero status 127
real 0.22
user 0.19
sys 0.02

Will it cause any problems if I try to install a different architecture as a target? Provided that I select an older one, of course.

**Comment by johannesring** [comment]
Looks like you didn't indent correctly. Try:

```
blas:
  use: openblas
  extra_flags: TARGET=SKYLAKE
```

**Comment by lobandolerpi** [comment]
Thank you very much  Johannes,

I tried with the correct indentation, and still was unable to find the
architecture, so I tried SANDYBRIDGE instead. According to wikipedia both
architectures have 14 (16 with fetch/retire) pipelines stages, whatever
these are.

The installation progress went on and found another error when building
dolfin. I am attaching the terminal screenshot and the CMake log, in case
it helps. It does not to me.

Terminal Screenshot:
https://dl.dropboxusercontent.com/u/37570775/FEniCs/TerminalScreenShot.png

LOG:
https://dl.dropboxusercontent.com/u/37570775/FEniCs/CMakeOutput.log

Records  /  Best regards   /  Saludos

Pedro Bonilla - Villalba.
